global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: node
    static_configs:    
      - targets:
        - 'node_exporter:9100'

  - job_name: cAdvisor
    static_configs:
      - targets:
        - 'cadvisor:8080'
  
